import netlify from '@netlify/vite-plugin-tanstack-start';
import tailwindcss from '@tailwindcss/vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import viteReact from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

import { blogPostsMeta } from './src/data/blog.meta.gen';

const blogPages = Object.keys(blogPostsMeta).map((slug) => ({
  path: `/blog/${slug}`,
}));

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  build: {
    target: 'es2022',
    rolldownOptions: {
      onwarn(warning, warn) {
        if (warning.code && ['SOURCEMAP_BROKEN'].includes(warning.code)) {
          return;
        }

        warn(warning);
      },
    },
  },
  plugins: [
    // Sitemap/RSS are generated by scripts/gen-blog.ts into public/
    tanstackStart({
      prerender: {
        enabled: true,
        crawlLinks: true,
        autoStaticPathsDiscovery: true,
        failOnError: true,
        filter: ({ path }) => !path.includes('#'),
      },
      pages: [
        { path: '/' },
        { path: '/blog' },
        { path: '/sudoku' },
        ...blogPages,
      ],
    }),
    netlify(),
    viteReact(),
    tailwindcss(),
  ],
});
