import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import matter from 'gray-matter';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { type BlogPost, type BlogPostMeta } from '~/types/blog';

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, '..', 'content', 'blog');
const dataDir = join(__dirname, '..', 'src', 'data');
const contentOutDir = join(dataDir, 'blog-content');
const publicDir = join(__dirname, '..', 'public');
const siteUrl = 'https://barrymichaeldoyle.com';

function readingMinutes(text: string): number {
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words / 200));
}

const posts: BlogPost[] = readdirSync(contentDir)
  .filter((file) => file.endsWith('.md'))
  .map((file) => {
    const raw = readFileSync(join(contentDir, file), 'utf8');
    const { data, content: markdownContent } = matter(raw);
    return {
      slug: file.replace('.md', ''),
      title: data.title || 'Untitled',
      date: data.date || '',
      description: data.description || '',
      content: markdownContent,
      readingMinutes: readingMinutes(markdownContent),
    };
  })
  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

const metaBySlug = posts.reduce(
  (acc, { content: _unused, ...meta }) => {
    void _unused;
    acc[meta.slug] = meta;
    return acc;
  },
  {} as Record<string, BlogPostMeta>
);

mkdirSync(contentOutDir, { recursive: true });

for (const post of posts) {
  writeFileSync(
    join(contentOutDir, `${post.slug}.gen.ts`),
    `// Generated by scripts/gen-blog.ts — do not edit.
export const content = ${JSON.stringify(post.content)};
`
  );
}

const metaFile = `// This file was automatically generated by scripts/gen-blog.ts.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { type BlogPostMeta } from '~/types/blog';

export const blogPostsMeta: Record<string, BlogPostMeta> = ${JSON.stringify(metaBySlug, null, 2)};
`;

writeFileSync(join(dataDir, 'blog.meta.gen.ts'), metaFile);

const loaderFile = `// This file was automatically generated by scripts/gen-blog.ts.
// You should NOT make any changes in this file as it will be overwritten.

const contentLoaders: Record<string, () => Promise<string>> = {
${posts
  .map(
    (post) =>
      `  '${post.slug}': async () => (await import('./blog-content/${post.slug}.gen')).content,`
  )
  .join('\n')}
};

export async function loadBlogContent(slug: string): Promise<string | undefined> {
  const loader = contentLoaders[slug];
  if (!loader) return undefined;
  return loader();
}
`;

writeFileSync(join(dataDir, 'blog.content.ts'), loaderFile);

const staticPages = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/blog', changefreq: 'weekly', priority: '0.8' },
];

const urls = [
  ...staticPages.map(
    (page) => `  <url>
    <loc>${siteUrl}${page.path}</loc>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`
  ),
  ...posts.map(
    (post) => `  <url>
    <loc>${siteUrl}/blog/${post.slug}</loc>
    ${post.date ? `<lastmod>${post.date}</lastmod>` : ''}
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`
  ),
].join('\n');

writeFileSync(
  join(publicDir, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
);

writeFileSync(
  join(publicDir, 'robots.txt'),
  `User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`
);
