import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import matter from 'gray-matter';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { type BlogPost, type BlogPostMeta } from '~/types/blog';

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, '..', 'content', 'blog');
const dataDir = join(__dirname, '..', 'src', 'data');
const contentOutDir = join(dataDir, 'blog-content');
const publicDir = join(__dirname, '..', 'public');
const siteUrl = 'https://barrymichaeldoyle.com';
const soUserId = 2111515;
const soGenFile = join(dataDir, 'stackoverflow.gen.ts');

function readingMinutes(text: string): number {
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words / 200));
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

const posts: BlogPost[] = readdirSync(contentDir)
  .filter((file) => file.endsWith('.md'))
  .map((file) => {
    const raw = readFileSync(join(contentDir, file), 'utf8');
    const { data, content: markdownContent } = matter(raw);
    return {
      slug: file.replace('.md', ''),
      title: data.title || 'Untitled',
      date: data.date || '',
      description: data.description || '',
      content: markdownContent,
      readingMinutes: readingMinutes(markdownContent),
    };
  })
  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

const metaBySlug = posts.reduce(
  (acc, { content: _unused, ...meta }) => {
    void _unused;
    acc[meta.slug] = meta;
    return acc;
  },
  {} as Record<string, BlogPostMeta>
);

mkdirSync(contentOutDir, { recursive: true });

for (const post of posts) {
  writeFileSync(
    join(contentOutDir, `${post.slug}.gen.ts`),
    `// Generated by scripts/gen-blog.ts — do not edit.
export const content = ${JSON.stringify(post.content)};
`
  );
}

const metaFile = `// This file was automatically generated by scripts/gen-blog.ts.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { type BlogPostMeta } from '~/types/blog';

export const blogPostsMeta: Record<string, BlogPostMeta> = ${JSON.stringify(metaBySlug, null, 2)};
`;

writeFileSync(join(dataDir, 'blog.meta.gen.ts'), metaFile);

const loaderFile = `// This file was automatically generated by scripts/gen-blog.ts.
// You should NOT make any changes in this file as it will be overwritten.

const contentLoaders: Record<string, () => Promise<string>> = {
${posts
  .map(
    (post) =>
      `  '${post.slug}': async () =>\n    (await import('./blog-content/${post.slug}.gen')).content,`
  )
  .join('\n')}
};

export async function loadBlogContent(
  slug: string
): Promise<string | undefined> {
  const loader = contentLoaders[slug];
  if (!loader) return undefined;
  return loader();
}
`;

writeFileSync(join(dataDir, 'blog.content.ts'), loaderFile);

const staticPages = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/blog', changefreq: 'weekly', priority: '0.8' },
];

const urls = [
  ...staticPages.map(
    (page) => `  <url>
    <loc>${siteUrl}${page.path}</loc>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`
  ),
  ...posts.map(
    (post) => `  <url>
    <loc>${siteUrl}/blog/${post.slug}</loc>
    ${post.date ? `<lastmod>${post.date}</lastmod>` : ''}
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`
  ),
].join('\n');

writeFileSync(
  join(publicDir, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
);

const rssItems = posts
  .map((post) => {
    const link = `${siteUrl}/blog/${post.slug}`;
    const pubDate = post.date
      ? new Date(`${post.date}T00:00:00.000Z`).toUTCString()
      : new Date().toUTCString();

    return `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${link}</link>
      <guid isPermaLink="true">${link}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${escapeXml(post.description)}</description>
    </item>`;
  })
  .join('\n');

writeFileSync(
  join(publicDir, 'rss.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Barry Michael Doyle</title>
    <link>${siteUrl}/blog</link>
    <description>Writing from Barry Michael Doyle on software engineering, open source, and building products.</description>
    <language>en-za</language>
    <atom:link href="${siteUrl}/rss.xml" rel="self" type="application/rss+xml" />
${rssItems}
  </channel>
</rss>
`
);

writeFileSync(
  join(publicDir, 'robots.txt'),
  `User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`
);

async function generateStackOverflowFlair() {
  try {
    const response = await fetch(
      `https://api.stackexchange.com/2.3/users/${soUserId}?order=desc&sort=reputation&site=stackoverflow`
    );

    if (!response.ok) {
      throw new Error(`Stack Overflow API responded with ${response.status}`);
    }

    const payload = (await response.json()) as {
      items?: Array<{
        reputation: number;
        badge_counts: { gold: number; silver: number; bronze: number };
        display_name: string;
        link: string;
      }>;
    };

    const user = payload.items?.[0];
    if (!user) {
      throw new Error('No Stack Overflow user found');
    }

    const flair = {
      reputation: user.reputation,
      badgeCounts: user.badge_counts,
      displayName: user.display_name,
      link: user.link,
      fetchedAt: new Date().toISOString(),
    };

    writeFileSync(
      soGenFile,
      `// Generated by scripts/gen-blog.ts — do not edit.
export const stackOverflowFlair = ${JSON.stringify(flair, null, 2)} as const;
`
    );
    console.log(
      `[gen] Stack Overflow flair updated (${flair.reputation.toLocaleString()} reputation)`
    );
  } catch (error) {
    console.warn(
      '[gen] Failed to refresh Stack Overflow flair; keeping previous data if present.',
      error
    );
  }
}

await generateStackOverflowFlair();
