// This file was automatically generated by scripts/gen-blog.ts.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { type BlogPostMeta } from '~/types/blog';

export const blogPostsMeta: Record<string, BlogPostMeta> = {
  "patch-pulse-2026-q2": {
    "slug": "patch-pulse-2026-q2",
    "title": "Why I Built Patch Pulse",
    "date": "2026-04-12",
    "description": "The problem that led me to build Patch Pulse, from Slack notifications to a monorepo-aware CLI and an in-progress VS Code extension.",
    "readingMinutes": 5
  },
  "starting-over": {
    "slug": "starting-over",
    "title": "If I could start my dev career again: Tips for Newbies",
    "date": "2023-09-11",
    "description": "A look at what I would do differently if I were to start over in my career",
    "readingMinutes": 5
  }
};
