// Generated by scripts/gen-blog.ts — do not edit.
export const stackOverflowFlair = {
  "reputation": 10776,
  "badgeCounts": {
    "bronze": 162,
    "silver": 99,
    "gold": 34
  },
  "displayName": "Barry Michael Doyle",
  "link": "https://stackoverflow.com/users/2111515/barry-michael-doyle",
  "fetchedAt": "2026-07-09T14:46:45.517Z"
} as const;
